#!/bin/python3

import math
import os
import random
import re
import sys


#
# Complete the 'countFamilyLogins' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING_ARRAY logins as parameter.

def rotate(s):
    s = list(s)
    for i in range(len(s)):
        if s[i]=='z':
            s[i] ='a'
        else:
            s[i] = chr(ord(s[i])+1)
    return ''.join(s)

def countFamilyLogins(logins):
    
    pair = {}
    n = len(logins)
    for l in logins:
        if l not in pair:
            pair[l] = rotate(l)
    count = 0
    for i in range(n):
        for j in range(i+1, n):
            if pair[logins[i]]==logins[j] or pair[logins[j]]==logins[i]:
                count+=1
    return count
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    logins_count = int(input().strip())

    logins = []

    for _ in range(logins_count):
        logins_item = input()
        logins.append(logins_item)

    result = countFamilyLogins(logins)

    fptr.write(str(result) + '\n')

    fptr.close()
